// Flat-config wrapper around eslint-config-expo. The Expo preset already ships
// TypeScript + React + React-Native + import defaults, so we intentionally do
// NOT re-declare those plugins here. Every rule downgrade below has a matching
// entry in docs/REFACTOR_PLAN.md Follow-ups — the goal of phase 0 is a passing
// lint run on the untouched tree, real fixes are their own phase.
const expoConfig = require('eslint-config-expo/flat');

module.exports = [
  ...expoConfig,
  {
    rules: {
      // Every rule downgraded during Phase 0 has since been paid down:
      //   - `react-hooks/rules-of-hooks`: declined.tsx reads
      //      useSafeAreaInsets() ABOVE the early `if (loading) return …`.
      //   - `react-hooks/refs`: _layout.tsx stores the splash
      //      `Animated.Value` in `useState(() => new Animated.Value(1))[0]`,
      //      not `useRef(new Animated.Value(1)).current`.
      //   - `react-hooks/exhaustive-deps`: every intentional mount-only
      //      effect carries a per-line disable with a justification. New
      //      violations must either add the missing dep or add a similar
      //      disable-line — silent suppression is not allowed.
      //   - `react-hooks/set-state-in-effect`: fires on every setState
      //      inside an effect, even async ones that only touch state in
      //      a resolved-promise microtask. Bootstrap fetches carry a
      //      per-line disable with the same justification pattern.
      // All four rules run at their default `error` level. Future
      // regressions fail lint in CI.
    },
  },
  {
    // Jest mock factories run before ES imports resolve, so `require()`
    // inside them is the officially blessed pattern. `jest.mock(...)` calls
    // also have to sit above `import` statements (Jest hoists them, but the
    // source order matters for readability) — `import/first` would otherwise
    // fight the intended test setup.
    files: ['tests/**/*.{ts,tsx,js}'],
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
      'import/first': 'off',
    },
  },
  {
    ignores: [
      'node_modules/**',
      '.expo/**',
      'dist/**',
      'build/**',
      'ios/**',
      'android/**',
      'coverage/**',
      // Vendored jsQR source — auto-generated by scripts/vendor-jsqr.mjs
      // from the installed npm copy. Must remain byte-identical.
      'lib/vendor/**',
    ],
  },
];
