// Flat-config wrapper around eslint-config-expo. The Expo preset already ships
// TypeScript + React + React-Native + import defaults, so we intentionally do
// NOT re-declare those plugins here. Every rule downgrade below has a matching
// entry in docs/REFACTOR_PLAN.md Follow-ups — the goal of phase 0 is a passing
// lint run on the untouched tree, real fixes are their own phase.
const expoConfig = require('eslint-config-expo/flat');

module.exports = [
  ...expoConfig,
  {
    rules: {
      // Existing hooks may not satisfy exhaustive-deps.
      'react-hooks/exhaustive-deps': 'warn',
      // React 19 introduced an aggressive set-state-in-effect check that the
      // existing bootstrap effects trip. Rule stays off until we have a
      // dedicated refactor phase to address it.
      'react-hooks/set-state-in-effect': 'off',
      // The two rules that were downgraded during Phase 0 have been fixed:
      //   - `react-hooks/rules-of-hooks`: declined.tsx now reads
      //      useSafeAreaInsets() ABOVE the early `if (loading) return …`.
      //   - `react-hooks/refs`: _layout.tsx now stores the splash
      //      `Animated.Value` in `useState(() => new Animated.Value(1))[0]`,
      //      not `useRef(new Animated.Value(1)).current`.
      // Both rules run at their default `error` level now — future
      // introductions of either pattern will fail lint in CI.
    },
  },
  {
    // Jest mock factories run before ES imports resolve, so `require()`
    // inside them is the officially blessed pattern. `jest.mock(...)` calls
    // also have to sit above `import` statements (Jest hoists them, but the
    // source order matters for readability) — `import/first` would otherwise
    // fight the intended test setup.
    files: ['tests/**/*.{ts,tsx,js}'],
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
      'import/first': 'off',
    },
  },
  {
    ignores: [
      'node_modules/**',
      '.expo/**',
      'dist/**',
      'build/**',
      'ios/**',
      'android/**',
      'coverage/**',
      // Vendored jsQR source — auto-generated by scripts/vendor-jsqr.mjs
      // from the installed npm copy. Must remain byte-identical.
      'lib/vendor/**',
    ],
  },
];
